### ISSUE TITLE
Create a Pomodoro timer example with WebGL

### ISSUE THREAD

**Issue by armiol** [TeamDev-IP/JxBrowser-Gallery#10]
In scope of this task, one more real-world and useful application should be created — a Pomodoro timer.

## Specifications

* Supported environments: **macOS**, in its first version.
* Tech stack: **JxBrowser, Compose Multiplatform, WebGL**.
* Tray application, similar to Jetbrains Toolbox — which is also a Compose Multiplatform app.
* Allows setting a single timer in one of modes:
    * Pomodoro — 25:00,
    * Short break — 05:00,
    * Long break — 15:00.

Inspired by [Pomofocus](https://pomofocus.io).

## UI

* Each mode is displayed as a animated WebGL model on a transparent background. So, no rectangular window!
    * Pomodoro — a tomato, or a remaining piece of tomato (cut) according to the amount of time remaining.
    * Short break — a semi-transparent coffee cup of espresso, with an amount of liquid proportional to the remaining time.
    * Long break — a semi-transparent tall cup of cappuchino, again, with an amount of drink proportional to the remaining time.
* Being "minimized", the tray symbol displays the remaining time, colored after the respective mode.

## Further expansion

Ultimately, this should become a paid app sold via Mac AppStore.

* Task list (with an ability to use GitHub issue link, expanding itself).
* Reports on time spent on each task per day, or per pre-selected period of time (week, month, etc).

## Checklist

- [x] TeamDev-IP/JxBrowser-Kotlin#112 
- [x] TeamDev-IP/JxBrowser-Kotlin#113
- [x] TeamDev-IP/JxBrowser-Kotlin#126
